services:
  - type: web
    name: backend-equipo
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "MÃ³dulo Usuario API"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: JWT_SECRET
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: mongodb
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: equipo
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FRONTEND_URL
        sync: false
      - key: FACEBOOK_CLIENT_ID
        sync: false
      - key: FACEBOOK_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_REDIRECT_URI
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
    healthCheckPath: /up
    plan: free
    region: oregon
